baseURL = "https://yann.mandragor.org/"
languageCode = "en-us"
title = "Yann Hamon"
theme = "yann.mandragor.org"
contentDir = "content"
staticDir = ["static"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true


